title: Blogosaurus
description: "A hacker-friendly showroom for the NooboTools collection."
baseurl: "/Nooblogaurus"
url: "https://noobosaurusblog.github.io"
markdown: kramdown
highlighter: rouge
theme: null
collections:
  tools:
    output: true
    permalink: /tools/:name/
permalink: pretty
defaults:
  - scope:
      path: ""
    values:
      layout: default
